#!/usr/bin/env python3
"""Generate MIDI note -> phase increment table for synth.v.

Sample rate: 200000 / 4 = 50000 Hz
Phase accumulator: 16-bit
increment = round(freq / 50000 * 65536)
"""
import math, sys

SAMPLE_RATE = 50000
ACC_SIZE = 65536
NOTE_OFFSET = 36   # input 0 → MIDI 36 (C2), input 63 → MIDI 99 (Eb7)
N_NOTES = 64

lines = ["// Auto-generated by py/gen_note_table.py",
         f"// 6-bit input → MIDI {NOTE_OFFSET}–{NOTE_OFFSET+N_NOTES-1}, 50kHz sample rate, 16-bit accumulator",
         "always @(*) begin",
         "    case (midi_note)"]

for i in range(N_NOTES):
    n = i + NOTE_OFFSET
    freq = 440.0 * (2.0 ** ((n - 69) / 12.0))
    inc = min(int(round(freq / SAMPLE_RATE * ACC_SIZE)), 65535)
    lines.append(f"        6'd{i}: phase_inc = 16'd{inc};  // MIDI {n}  {freq:.2f} Hz")

lines += ["        default: phase_inc = 16'd0;",
          "    endcase",
          "end"]

out = "\n".join(lines) + "\n"

path = sys.argv[1] if len(sys.argv) > 1 else "src/note_tbl_case.vh"
with open(path, "w") as f:
    f.write(out)
print(f"Written {len(lines)} lines to {path}")
