`default_nettype none

// Triangle oscillator with exponential release envelope.
// Accepts MIDI note number; gate high = note on, gate low = exponential decay.
// Outputs 1-bit sigma-delta PWM and 16-bit audio sample for simulation.
//
// Clock: 200 kHz  (info.yaml: clock_hz: 200000)
// Sample rate: clk/4 = 50 kHz
// Phase accumulator: 16-bit
// Envelope decay: env -= env >> 13  (τ ≈ 164 ms at 50 kHz)
module synth (
    input  wire        clk,
    input  wire        rst_n,
    input  wire  [5:0] midi_note,    // note index 0-63 → MIDI 36-99 (C2-Eb7)
    input  wire        gate,         // 1 = note on, 0 = release
    output wire [15:0] audio_sample, // unsigned 16-bit for simulation
    output reg         audio_out     // 1-bit sigma-delta PWM
);

// ── Sample clock divider: /4 → 50 kHz ──────────────────────────────────────
reg [1:0] sample_div;
wire sample_tick = &sample_div;

// ── Triangle oscillator ─────────────────────────────────────────────────────
reg [15:0] phase;
reg [15:0] phase_inc;

// Fold phase at midpoint to get triangle: 0→32767→0
wire [15:0] tri_wave = phase[15] ? ~phase : phase;

// ── Exponential envelope ────────────────────────────────────────────────────
reg [15:0] env;
reg gate_prev;

// ── Mix: scale triangle by envelope ────────────────────────────────────────
// tri_wave ∈ [0, 32767], env ∈ [0, 65535]
// product [31:0]; take [30:15] for 16-bit result
wire [31:0] tri_env = tri_wave * env;
// Convert signed [-32768..32767] → unsigned [0..65535] for sigma-delta
assign audio_sample = tri_env[30:15] ^ 16'h8000;

// ── Sigma-delta modulator (runs at full 200 kHz) ────────────────────────────
reg [15:0] sd_accum;
wire [16:0] sd_next = sd_accum + audio_sample;

// ── Note frequency table (50 kHz sample rate, 16-bit accumulator) ───────────
// Generated by py/gen_note_table.py
// 6-bit input → MIDI 36–99, 50kHz sample rate, 16-bit accumulator
always @(*) begin
    case (midi_note)
        6'd0: phase_inc = 16'd86;  // MIDI 36  65.41 Hz
        6'd1: phase_inc = 16'd91;  // MIDI 37  69.30 Hz
        6'd2: phase_inc = 16'd96;  // MIDI 38  73.42 Hz
        6'd3: phase_inc = 16'd102;  // MIDI 39  77.78 Hz
        6'd4: phase_inc = 16'd108;  // MIDI 40  82.41 Hz
        6'd5: phase_inc = 16'd114;  // MIDI 41  87.31 Hz
        6'd6: phase_inc = 16'd121;  // MIDI 42  92.50 Hz
        6'd7: phase_inc = 16'd128;  // MIDI 43  98.00 Hz
        6'd8: phase_inc = 16'd136;  // MIDI 44  103.83 Hz
        6'd9: phase_inc = 16'd144;  // MIDI 45  110.00 Hz
        6'd10: phase_inc = 16'd153;  // MIDI 46  116.54 Hz
        6'd11: phase_inc = 16'd162;  // MIDI 47  123.47 Hz
        6'd12: phase_inc = 16'd171;  // MIDI 48  130.81 Hz
        6'd13: phase_inc = 16'd182;  // MIDI 49  138.59 Hz
        6'd14: phase_inc = 16'd192;  // MIDI 50  146.83 Hz
        6'd15: phase_inc = 16'd204;  // MIDI 51  155.56 Hz
        6'd16: phase_inc = 16'd216;  // MIDI 52  164.81 Hz
        6'd17: phase_inc = 16'd229;  // MIDI 53  174.61 Hz
        6'd18: phase_inc = 16'd242;  // MIDI 54  185.00 Hz
        6'd19: phase_inc = 16'd257;  // MIDI 55  196.00 Hz
        6'd20: phase_inc = 16'd272;  // MIDI 56  207.65 Hz
        6'd21: phase_inc = 16'd288;  // MIDI 57  220.00 Hz
        6'd22: phase_inc = 16'd306;  // MIDI 58  233.08 Hz
        6'd23: phase_inc = 16'd324;  // MIDI 59  246.94 Hz
        6'd24: phase_inc = 16'd343;  // MIDI 60  261.63 Hz  (C4)
        6'd25: phase_inc = 16'd363;  // MIDI 61  277.18 Hz
        6'd26: phase_inc = 16'd385;  // MIDI 62  293.66 Hz
        6'd27: phase_inc = 16'd408;  // MIDI 63  311.13 Hz
        6'd28: phase_inc = 16'd432;  // MIDI 64  329.63 Hz
        6'd29: phase_inc = 16'd458;  // MIDI 65  349.23 Hz
        6'd30: phase_inc = 16'd485;  // MIDI 66  369.99 Hz
        6'd31: phase_inc = 16'd514;  // MIDI 67  392.00 Hz
        6'd32: phase_inc = 16'd544;  // MIDI 68  415.30 Hz
        6'd33: phase_inc = 16'd577;  // MIDI 69  440.00 Hz  (A4)
        6'd34: phase_inc = 16'd611;  // MIDI 70  466.16 Hz
        6'd35: phase_inc = 16'd647;  // MIDI 71  493.88 Hz
        6'd36: phase_inc = 16'd686;  // MIDI 72  523.25 Hz
        6'd37: phase_inc = 16'd727;  // MIDI 73  554.37 Hz
        6'd38: phase_inc = 16'd770;  // MIDI 74  587.33 Hz
        6'd39: phase_inc = 16'd816;  // MIDI 75  622.25 Hz
        6'd40: phase_inc = 16'd864;  // MIDI 76  659.26 Hz
        6'd41: phase_inc = 16'd915;  // MIDI 77  698.46 Hz
        6'd42: phase_inc = 16'd970;  // MIDI 78  739.99 Hz
        6'd43: phase_inc = 16'd1028;  // MIDI 79  783.99 Hz
        6'd44: phase_inc = 16'd1089;  // MIDI 80  830.61 Hz
        6'd45: phase_inc = 16'd1153;  // MIDI 81  880.00 Hz
        6'd46: phase_inc = 16'd1222;  // MIDI 82  932.33 Hz
        6'd47: phase_inc = 16'd1295;  // MIDI 83  987.77 Hz
        6'd48: phase_inc = 16'd1372;  // MIDI 84  1046.50 Hz
        6'd49: phase_inc = 16'd1453;  // MIDI 85  1108.73 Hz
        6'd50: phase_inc = 16'd1540;  // MIDI 86  1174.66 Hz
        6'd51: phase_inc = 16'd1631;  // MIDI 87  1244.51 Hz
        6'd52: phase_inc = 16'd1728;  // MIDI 88  1318.51 Hz
        6'd53: phase_inc = 16'd1831;  // MIDI 89  1396.91 Hz
        6'd54: phase_inc = 16'd1940;  // MIDI 90  1479.98 Hz
        6'd55: phase_inc = 16'd2055;  // MIDI 91  1567.98 Hz
        6'd56: phase_inc = 16'd2177;  // MIDI 92  1661.22 Hz
        6'd57: phase_inc = 16'd2307;  // MIDI 93  1760.00 Hz
        6'd58: phase_inc = 16'd2444;  // MIDI 94  1864.66 Hz
        6'd59: phase_inc = 16'd2589;  // MIDI 95  1975.53 Hz
        6'd60: phase_inc = 16'd2743;  // MIDI 96  2093.00 Hz
        6'd61: phase_inc = 16'd2906;  // MIDI 97  2217.46 Hz
        6'd62: phase_inc = 16'd3079;  // MIDI 98  2349.32 Hz
        6'd63: phase_inc = 16'd3262;  // MIDI 99  2489.02 Hz
        default: phase_inc = 16'd0;
    endcase
end

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        sample_div <= 2'b0;
        phase      <= 16'b0;
        env        <= 16'b0;
        gate_prev  <= 1'b0;
        sd_accum   <= 16'b0;
        audio_out  <= 1'b0;
    end else begin
        // Sigma-delta runs every clock
        sd_accum  <= sd_next[15:0];
        audio_out <= sd_next[16];

        // Sample-rate logic at 50 kHz
        sample_div <= sample_div + 1;
        if (sample_tick) begin
            phase     <= phase + phase_inc;
            gate_prev <= gate;

            if (gate) begin
                // Note on: hold envelope at maximum
                env <= 16'hFFFF;
            end else begin
                // Note off: exponential decay (τ ≈ 2^13 / 50000 ≈ 164 ms)
                env <= env - (env >> 13);
            end
        end
    end
end

endmodule
